### ISSUE TITLE
(Potion stacksize) 1.10.2-Crash w/ Extra Utils 2

### ISSUE THREAD

**Issue by WenXin20** [spikespaz/EssentialAdditions#10]
Forge 2221
[Extra Utils](https://minecraft.curseforge.com/projects/extra-utilities/files/2381549) v1.3.0
Essential Additions v1.6.1
The mod crashes with Extra Utils at the end of the game load.
[Crash Report](http://pastebin.com/DAgkGimL)

**Comment by spikespaz** [comment]
Thanks for your report. I'll have a fix out with the next version, which is coming soon. It is a problem with the custom potion stacksizes, when the Forge potion helper detects a potion stack greater than 1 it crashes. I will either disable this or add a config file to turn it off. It will be turned off by default.

**Comment by spikespaz** [comment]
It will not have a configuration option, it will be removed entirely as it also affects vanilla behavior in the brewing stand.

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by spikespaz** [comment]
This issue has been fixed in a release build, and therefore will be closed. Thank you for your contribution.
View the release here: https://github.com/spikespaz/EssentialAdditions/releases/tag/v1.6.3
